install:
    - sudo apt-get update
    - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 libcurl4-openssl-dev php5-curl libapache2-mod-php5 php5-mysql php5-intl php5-cli curl
    - sudo DEBIAN_FRONTEND=noninteractive apt-get -y --force-yes install mysql-server

    - curl -sS https://getcomposer.org/installer | php
    - sudo mv composer.phar /usr/bin/composer

    - sudo cp .playwithme/apache-vhost.conf /etc/apache2/sites-available/default
    - sudo /etc/init.d/apache2 restart
    - echo "127.0.0.1    eventator.l" | sudo tee -a /etc/hosts

    - cp app/config/parameters.yml.dist app/config/parameters.yml

    - composer install --dev --prefer-dist
    - app/console do:da:cr
    - app/console do:sc:cr

    - app/console assetic:dump --env=prod
    - app/console --env=prod --no-debug --symlink assets:install web

    # get the cache warmed up and with the right permissiosn
    - chmod -R 777 app/cache app/logs
    - app/console --env=dev cache:warmup
    - chmod -R 777 app/cache app/logs
    - wget http://eventator.l/
    - sudo chmod -R 777 app/cache app/logs
