event_homepage:
    pattern:  /
    defaults: { _controller: EventEventBundle:Event:index }

_components:
    resource: routing/components.yml
    prefix:   /

_backend:
    resource: routing/backend.yml
    prefix:   /event/admin

admin_login:
    pattern:  /event/admin/login
    defaults: { _controller: EventEventBundle:Backend/Security:login }

admin_check:
    pattern:  /event/admin/login_check
    defaults: { _controller: EventEventBundle:Backend/Security:check }

admin_logout:
    pattern:  /event/admin/logout
    defaults: { _controller: EventEventBundle:Backend/Security:logout }
