event_homepage:
    pattern:  /
    defaults: { _controller: EventEventBundle:Event:index }

event_component_carousel:
    pattern: /carousel
    defaults: { _controller: EventEventBundle:Event:carousel }

_backend:
    resource: routing/backend.yml
    prefix:   /admin

admin_login:
    pattern:  /admin/login
    defaults: { _controller: EventEventBundle:Backend/Security:login }

admin_check:
    pattern:  /admin/login_check
    defaults: { _controller: EventEventBundle:Backend/Security:check }

admin_logout:
    pattern:  /admin/logout
    defaults: { _controller: EventEventBundle:Backend/Security:logout }
