backend_dashboard:
    pattern:  /
    defaults: { _controller: EventEventBundle:Backend/Dashboard:index }

backend_settings:
    pattern:  /
    defaults: { _controller: EventEventBundle:Backend/Dashboard:setting }

backend_program:
    pattern:  /
    defaults: { _controller: EventEventBundle:Backend/Program:index }

backend_speaker:
    pattern:  /
    defaults: { _controller: EventEventBundle:Backend/Speaker:index }

backend_sponsor:
    pattern:  /
    defaults: { _controller: EventEventBundle:Backend/Sponsor:index }
