event_component_carousel:
    path:  /carousel
    defaults: { _controller: EventEventBundle:Event:carousel }

event_component_speakers:
    path:  /speakers
    defaults: { _controller: EventEventBundle:Event:speakers }

event_component_about:
    path:  /about
    defaults: { _controller: EventEventBundle:Event:aboutSymfony }

event_component_venue:
    path:  /venue
    defaults: { _controller: EventEventBundle:Event:venue }

event_component_conferences:
    path:  /conferences
    defaults: { _controller: EventEventBundle:Event:conferences }

event_component_schedule:
    path:  /schedule
    defaults: { _controller: EventEventBundle:Event:schedule }

event_component_sponsors:
    path:  /sponsors
    defaults: { _controller: EventEventBundle:Event:sponsors }

event_component_organizers:
    path:  /sponsors
    defaults: { _controller: EventEventBundle:Event:organizers }

event_component_contact:
    path:  /contact
    defaults: { _controller: EventEventBundle:Event:contact }

event_component_call_for_paper:
    path:  /call-for-paper-mod
    defaults: { _controller: EventEventBundle:Event:callForPaper }
    requirements:
        methods: POST

event_component_call_for_paper_view:
    path:  /call-for-paper
    defaults: { _controller: EventEventBundle:Event:callForPaperView }
    requirements:
        methods: POST

event_component_ticket:
    path: /buy-ticket
    defaults: { _controller: EventEventBundle:Event:buyTicket }

tickets_payment_success:
    path: /payment-success
    defaults: { _controller: EventEventBundle:Event:ticketPaymentSuccess }

tickets_handle_liqpay:
    path: /liqpay-handle
    defaults: { _controller: EventEventBundle:Event:handleLiqPayRequest }

ticketPDF:
    path: /ticketPDF
    defaults: { _controller: EventEventBundle:Event:viewPDFHtml }

update_total:
    path: /update-total-ajax
    defaults: { _controller: EventEventBundle:Event:updateTotalAjax }

lang_switch:
    path:  /change-locale/{lang}
    defaults: { _controller: EventEventBundle:Event:changeLanguage, lang: null }

event_component_workshop:
    path: /buy-workshop
    defaults: { _controller: EventEventBundle:Event:buyWorkshop }

workshops_payment_success:
    path: /workshop-payment-success
    defaults: { _controller: EventEventBundle:Event:workshopPaymentSuccess }

workshops_handle_liqpay:
    path: /workshop-liqpay-handle
    defaults: { _controller: EventEventBundle:Event:handleWorkshopLiqPayRequest }

workshopPDF:
    path: /workshopPDF
    defaults: { _controller: EventEventBundle:Event:viewWorkshopPDFHtml }
